FROM ubuntu:18.04

RUN apt-get update && apt-get -y upgrade &&  apt-get -y install apt-utils && \
	apt-get -y install \
    cmake \
    libantlr3c-dev \
    autoconf \
    gcc-arm-linux-gnueabi \
    g++ \
    libncurses5-dev \
    make \
    mercurial \
    default-jre-headless \
    wget \
    zlib1g-dev
