FROM debian:9.3

RUN apt-get update && apt-get -y install \
    autoconf \
    cmake \
    gcc-arm-linux-gnueabi \
    g++ \
    libncurses5-dev \
    make \
    libantlr3c-dev \
    mercurial \
    openjdk-8-jre-headless \
    wget \
    zlib1g-dev
