/* This file is Copyright University of Edinburgh 2018. For license details, see LICENSE. */

#pragma once

#include "genC/ssa/statement/SSABinaryArithmeticStatement.h"
#include "genC/ssa/statement/SSABitDepositStatement.h"
#include "genC/ssa/statement/SSABitExtractStatement.h"
#include "genC/ssa/statement/SSACallStatement.h"
#include "genC/ssa/statement/SSACastStatement.h"
#include "genC/ssa/statement/SSAConstantStatement.h"
#include "genC/ssa/statement/SSAControlFlowStatement.h"
#include "genC/ssa/statement/SSADeviceReadStatement.h"
#include "genC/ssa/statement/SSAIfStatement.h"
#include "genC/ssa/statement/SSAIntrinsicStatement.h"
#include "genC/ssa/statement/SSAJumpStatement.h"
#include "genC/ssa/statement/SSAMemoryReadStatement.h"
#include "genC/ssa/statement/SSAMemoryWriteStatement.h"
#include "genC/ssa/statement/SSAPhiStatement.h"
#include "genC/ssa/statement/SSARaiseStatement.h"
#include "genC/ssa/statement/SSAReadStructMemberStatement.h"
#include "genC/ssa/statement/SSARegisterStatement.h"
#include "genC/ssa/statement/SSAReturnStatement.h"
#include "genC/ssa/statement/SSASelectStatement.h"
#include "genC/ssa/statement/SSASwitchStatement.h"
#include "genC/ssa/statement/SSAUnaryArithmeticStatement.h"
#include "genC/ssa/statement/SSAVariableKillStatement.h"
#include "genC/ssa/statement/SSAVariableReadStatement.h"
#include "genC/ssa/statement/SSAVariableWriteStatement.h"
#include "genC/ssa/statement/SSAVectorExtractElementStatement.h"
#include "genC/ssa/statement/SSAVectorInsertElementStatement.h"
#include "genC/ssa/statement/SSAVectorShuffleStatement.h"
