/*
 * blockjit-abi.h
 *
 *  Created on: 6 Oct 2015
 *      Author: harry
 */

#ifndef INC_BLOCKJIT_BLOCKJIT_ABI_H_
#define INC_BLOCKJIT_BLOCKJIT_ABI_H_

#define X86Reg(X) captive::arch::x86::X

#define BLKJIT_REGS_BUILD_LAMBDA(q,l,w,b) [](unsigned i) -> const captive::arch::x86::X86Register& { switch(i) { case 8: return q; case 4: return l; case 2: return w; case 1: return b; default: assert(false); return X86Reg(REG_RIZ); } }
#define REGS_RAX BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RAX), X86Reg(REG_EAX), X86Reg(REG_AX), X86Reg(REG_AL))
#define REGS_RBX BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RBX), X86Reg(REG_EBX), X86Reg(REG_BX), X86Reg(REG_BL))
#define REGS_RCX BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RCX), X86Reg(REG_ECX), X86Reg(REG_CX), X86Reg(REG_CL))
#define REGS_RDX BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RDX), X86Reg(REG_EDX), X86Reg(REG_DX), X86Reg(REG_DL))

#define REGS_RBP BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RBP), X86Reg(REG_EBP), X86Reg(REG_BP), X86Reg(REG_BPL))
#define REGS_RSP BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RSP), X86Reg(REG_ESP), X86Reg(REG_SP), X86Reg(REG_SPL))

#define REGS_RDI BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RDI), X86Reg(REG_EDI), X86Reg(REG_DI), X86Reg(REG_DIL))
#define REGS_RSI BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_RSI), X86Reg(REG_ESI), X86Reg(REG_SI), X86Reg(REG_SIL))

#define REGS_R8 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R8), X86Reg(REG_R8D), X86Reg(REG_R8W), X86Reg(REG_R8B))
#define REGS_R9 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R9), X86Reg(REG_R9D), X86Reg(REG_R9W), X86Reg(REG_R9B))
#define REGS_R10 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R10), X86Reg(REG_R10D), X86Reg(REG_R10W), X86Reg(REG_R10B))
#define REGS_R11 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R11), X86Reg(REG_R11D), X86Reg(REG_R11W), X86Reg(REG_R11B))
#define REGS_R12 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R12), X86Reg(REG_R12D), X86Reg(REG_R12W), X86Reg(REG_R12B))
#define REGS_R13 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R13), X86Reg(REG_R13D), X86Reg(REG_R13W), X86Reg(REG_R13B))
#define REGS_R14 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R14), X86Reg(REG_R14D), X86Reg(REG_R14W), X86Reg(REG_R14B))
#define REGS_R15 BLKJIT_REGS_BUILD_LAMBDA(X86Reg(REG_R15), X86Reg(REG_R15D), X86Reg(REG_R15W), X86Reg(REG_R15B))

#define BLKJIT_REGSTATE_REG X86Reg(REG_RBP)
#define BLKJIT_CPUSTATE_REG X86Reg(REG_R12)

#define BLKJIT_TEMPS_0 REGS_RDI
#define BLKJIT_TEMPS_1 REGS_RSI
#define BLKJIT_TEMPS_2 REGS_RDX

#define BLKJIT_ARG0 REGS_RDI
#define BLKJIT_ARG1 REGS_RSI
#define BLKJIT_ARG2 REGS_RDX

#define BLKJIT_RETURN REGS_R15

#define BLKJIT_NUM_ALLOCABLE 8

#define BLKJIT_FP_0 X86Reg(REG_XMM0)
#define BLKJIT_FP_1 X86Reg(REG_XMM1)
#define BLKJIT_FP_2 X86Reg(REG_XMM2)

#endif /* INC_BLOCKJIT_BLOCKJIT_ABI_H_ */
