FROM ubuntu:14.04

RUN apt-get update && apt-get -y install \
    autoconf \
    cmake \
    libantlr3c-dev \
    gcc-arm-linux-gnueabi \
    g++ \
    libncurses5-dev \
    make \
    mercurial \
    openjdk-7-jre-headless \
    wget \
    zlib1g-dev
