FROM base/archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
	autoconf \
	automake \
	arm-none-eabi-gcc \
    cmake \
    gcc \
	jre9-openjdk-headless \
	libantlr3c \
	mercurial \
	make \
	ncurses \
	openssh \
	wget \
	zlib \
    sdl2
	
