FROM base/archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
	libantlr3c \
    gcc \
    cmake \
	autoconf \
	automake \
	arm-none-eabi-gcc \
	jre9-openjdk-headless \
	mercurial \
	make \
	ncurses \
	openssh \
	wget \
	zlib
	
