/* This file is Copyright University of Edinburgh 2018. For license details, see LICENSE. */

#ifndef TESTHARNESSSETTINGS_H_
#define TESTHARNESSSETTINGS_H_

#define TEST_INSTRUCTION_PC_VAL 0x8db0
#define TEST_INSTRUCTION_MEMORY_ZONE_START 0x8898
#define TEST_INSTRUCTION_MEMORY_ZONE_END 0x8e38
#define TEST_INSTRUCTION_NOP_SLIDE_START 0x8e40
#define TEST_INSTRUCTION_NOP_SLIDE_END 0x963c

#endif /* TESTHARNESSSETTINGS_H_ */
